variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    LATEST_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build-push-docker-image-job:
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker info
        - docker ps
        - docker-compose up -d
