variables:
    IMAGE_NAME: "blocklistener-app"
    CONTAINER_NAME: "blocklistener-app"
    HOSTNAME: "blocklistener-app"

build-push-docker-image-job:
    image: docker:latest
    services:
        - docker:dind
    script:
        - echo "$ENV_FILE" > "$(pwd)/.env"
        - docker build -t $IMAGE_NAME .
        - current_container_running=$(docker ps -q --filter "ancestor=$IMAGE_NAME")
        # remove previous container if running
        - docker rm -f $CONTAINER_NAME &>/dev/null && echo 'Removed old container $CONTAINER_NAME'
        - docker run -d -p 3000:80 --restart=always --env-file=.env --network="main" --name=$CONTAINER_NAME --hostname=$HOSTNAME $IMAGE_NAME
