stages:
  - deploy

deploy_develop:
  stage: deploy
  script:
    - echo "Deploy to develop server"
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
  environment:
    name: develop
    url: https://$HEROKU_APP_NAME.herokuapp.com
