variables:
    IMAGE_NAME: "blocklistener-app"
    CONTAINER_NAME: "blocklistener-app"
    HOSTNAME: "blocklistener-app"

docker_build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build -t $IMAGE_NAME .
docker_deploy:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    script:
        - echo "$ENV_FILE" > "$(pwd)/.env"
        - current_container_running=$(docker ps -q --filter "ancestor=$IMAGE_NAME")
        # remove previous container if running
        - docker rm -f $CONTAINER_NAME &>/dev/null && echo 'Removed old container $CONTAINER_NAME'
        - docker run -d -p 3000:80 --restart=always --env-file=.env --network="main" --name=$CONTAINER_NAME --hostname=$HOSTNAME --log-driver=loki --log-opt loki-url="https://${GRAFANA_LOKI_USER}:${GRAFANA_LOKI_API_KEY}@logs-prod-008.grafana.net/loki/api/v1/push" --log-opt loki-retries=10 --log-opt loki-batch-size=400 --log-opt max-size="4m" --log-opt max-buffer-size="20m" --log-opt loki-timeout="15s" --log-opt mode="non-blocking" $IMAGE_NAME
        - rm "$(pwd)/.env"
