version: "3.7"
services:
    redis:
        container_name: "redis"
        image: redis
        ports:
            - "6379:6379"
    mongodb:
        image: mongo:5.0
        container_name: "mongodb"
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./.volumes/mongodb-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=blocklistener
            - MONGO_INITDB_ROOT_PASSWORD=S3cret
        networks:
            - main
    rabbitmq:
        #image: rabbitmq:3-management-alpine
        build:
            context: .
            dockerfile: ./Dockerfile.rabbit
        container_name: "rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./.volumes/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.volumes/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - main

networks:
    main:
        driver: bridge
