version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        env_file: .env
        depends_on:
            - rabbitmq
            - mongodb
        links:
            - mongodb
            - rabbitmq
        ports:
            - 80:80
        networks:
            - main
    mongodb:
        image: mongo:5.0
        container_name: "mongodb"
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./.volumes/mongodb-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=blocklistener
            - MONGO_INITDB_ROOT_PASSWORD=S3cret
        networks:
            - main
    rabbitmq:
        #image: rabbitmq:3-management-alpine
        build:
            context: .
            dockerfile: ./Dockerfile.rabbit
        container_name: "rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./.volumes/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.volumes/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - main

networks:
    main:
        driver: bridge
