{
 "title": "Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Halts",
   "type": "stat",
   "description": "Counter of times that BlockListener has stopped publishing new blocks due to a busy SaveTx queue",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "db_66299",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_hit\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND type = 'block-listener.new-block.cool-down'\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_hit\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1663047215, 3)\n    AND toDateTime64(1663058015, 3)\n    AND type = 'block-listener.new-block.cool-down'\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "blocklistener_2"
    }
   ]
  },
  {
   "title": "Total Txs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "db_66299",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    1 as t,\n    count()\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type = 'save-tx.saved'\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    1 as t,\n    count()\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662452880,0)\n    AND toDateTime64(1663057680, 0)\n    AND type = 'save-tx.saved'\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "blocklistener_2"
    }
   ]
  },
  {
   "title": "Avg(Blocks)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "db_66299",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "\nSELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() \nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type = 'block-listener.new-block.saved'\nGROUP BY t\n\nORDER BY t\n\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() \nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1663046970,0)\n    AND toDateTime64(1663057770, 0)\n    AND type = 'block-listener.new-block.saved'\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "blocklistener_2"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Captured TXs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "db_66299",
     "dateTimeColDataType": "dt",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type = 'save-tx.saved'\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662296642,0)\n    AND toDateTime64(1662318242, 0)\n    AND type = 'save-tx.saved'\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "blocklistener_2"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit/Miss",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_hit\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND type LIKE 'cache.hit.%'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_hit\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662011507, 3)\n    AND toDateTime64(1662033107, 3)\n    AND type LIKE 'cache.hit.%'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      },
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_miss\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND type LIKE 'cache.miss.%'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_miss\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662011507, 3)\n    AND toDateTime64(1662033107, 3)\n    AND type LIKE 'cache.miss.%'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      }
     ]
    },
    {
     "title": "Finnhub Cache Hit/Miss",
     "type": "graph",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_hit\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND type LIKE 'cache.hit.finnhub.%'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_hit\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662011530, 3)\n    AND toDateTime64(1662033130, 3)\n    AND type LIKE 'cache.hit.finnhub.%'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      },
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_miss\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\n    AND type LIKE 'cache.miss.finnhub.%'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as cache_miss\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662011530, 3)\n    AND toDateTime64(1662033130, 3)\n    AND type LIKE 'cache.miss.finnhub.%'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      }
     ]
    }
   ]
  },
  {
   "title": "3rd parties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed JSON rpc calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as total\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type LIKE 'provider.call.failed%'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as total\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662316401,0)\n    AND toDateTime64(1662320001, 0)\n    AND type LIKE 'provider.call.failed%'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      }
     ]
    },
    {
     "title": "Covalent failed calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as total\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type LIKE 'covalent-api.call.failed.%'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as total\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1661931199,0)\n    AND toDateTime64(1661952799, 0)\n    AND type LIKE 'covalent-api.call.failed.%'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      }
     ]
    },
    {
     "title": "Finnhub failed calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as total\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type LIKE 'finnhub-api.call.failed.%'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count() as total\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1661931279,0)\n    AND toDateTime64(1661952879, 0)\n    AND type LIKE 'finnhub-api.call.failed.%'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      }
     ]
    }
   ]
  },
  {
   "title": "Wallets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Note",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
     "options": {
      "content": "Wallets = Unknown + Whales.\nWe should try to display the amount of whales against unknown as it is the real nice measure."
     },
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from, 3)\n    AND toDateTime64($to, 3)\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM db_66299.blocklistener\n\nWHERE\n    dt BETWEEN toDateTime64(1662012012, 3)\n    AND toDateTime64(1662033612, 3)\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener"
      }
     ]
    },
    {
     "title": "Discovered Wallets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type = 'save-wallet.saved'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1661931447,0)\n    AND toDateTime64(1661953047, 0)\n    AND type = 'save-wallet.saved'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      }
     ]
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tokens Discovered",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "db_66299",
       "dateTimeColDataType": "dt",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t, count() FROM $table WHERE dt BETWEEN toDateTime64($from, 3) AND toDateTime64($to, 3) GROUP BY t ORDER BY t",
       "query": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM $table\n\nWHERE\n    dt BETWEEN toDateTime64($from,0)\n    AND toDateTime64($to, 0)\n    AND type = 'save-token.saved'\nGROUP BY t\n\nORDER BY t\n",
       "rawQuery": "SELECT\n    toUnixTimestamp(toStartOfMinute(dt)) * 1000 as t,\n    count()\nFROM db_66299.blocklistener_2\n\nWHERE\n    dt BETWEEN toDateTime64(1662029885,0)\n    AND toDateTime64(1662033485, 0)\n    AND type = 'save-token.saved'\nGROUP BY t\n\nORDER BY t",
       "round": "0s",
       "table": "blocklistener_2"
      }
     ]
    }
   ]
  }
 ]
}