version: "3.7"
services:
    block-listener:
        container_name: block-listener
        ports:
            - 3001:3000
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ./.env.prod
